name: Run tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:


jobs:
  run_tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Run tests
        run: python tests.py